# Generated by Django 5.1.4 on 2025-01-16 10:16

import django.contrib.postgres.fields
import django.db.models.deletion
import siemrules.siemrules.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('identity', models.JSONField(default=siemrules.siemrules.models.default_identity, validators=[siemrules.siemrules.models.validate_identity])),
                ('labels', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), default=list, size=None)),
                ('tlp_level', models.CharField(choices=[('red', 'Red'), ('amber+strict', 'AMBER+STRICT'), ('amber', 'Amber'), ('green', 'Green'), ('clear', 'Clear')], default='red', max_length=128)),
                ('file', models.FileField(max_length=1024, upload_to=siemrules.siemrules.models.upload_to_func)),
                ('mimetype', models.CharField(max_length=512)),
                ('mode', models.CharField(max_length=256)),
                ('defang', models.BooleanField(default=True)),
                ('extract_text_from_image', models.BooleanField(default=True)),
                ('ai_provider', models.CharField(max_length=256)),
                ('detection_language', models.CharField(max_length=256)),
                ('markdown_file', models.FileField(max_length=256, null=True, upload_to=siemrules.siemrules.models.upload_to_func)),
                ('confidence', models.IntegerField(default=0, help_text='A value between `0`-`100`. `0` means confidence unknown. `1` is the lowest confidence score, `100` is the highest confidence score.')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FileImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=256, upload_to=siemrules.siemrules.models.upload_to_func)),
                ('name', models.CharField(max_length=256)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='siemrules.file')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('error', models.CharField(max_length=65536, null=True)),
                ('run_datetime', models.DateTimeField(auto_now_add=True)),
                ('completion_time', models.DateTimeField(default=None, null=True)),
                ('file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='siemrules.file')),
            ],
        ),
    ]
