# Generated by Django 5.1.4 on 2025-01-17 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siemrules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='defang',
            field=models.BooleanField(default=True, help_text='Whether to defang the observables in the blog. e.g. turns 1.1.1[.]1 to 1.1.1.1 for extraction. This is a file2txt setting. This is a file2txt setting. Default is `true`.'),
        ),
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(help_text='This will be assigned to the File and Report object created. Note, the names of each detection rule generated will be automatic. Max 256 characters. This is a txt2detection setting.', max_length=256),
        ),
    ]
