# Generated by Django 5.1.4 on 2025-01-17 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siemrules', '0002_alter_file_defang_alter_file_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='description',
        ),
    ]
