# Generated by Django 5.1.4 on 2025-01-17 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siemrules', '0003_remove_file_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='confidence',
            field=models.IntegerField(default=0),
        ),
    ]
