# Generated by Django 5.1.4 on 2025-01-22 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siemrules', '0004_alter_file_confidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='ignore_embedded_relationships',
            field=models.BooleanField(default=False),
        ),
    ]
