# Generated by Django 5.1.4 on 2025-03-25 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siemrules', '0005_file_ignore_embedded_relationships'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='detection_language',
        ),
    ]
