# Generated by Django 5.1.4 on 2025-04-03 10:56

import django.contrib.postgres.fields
import siemrules.siemrules.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siemrules', '0006_remove_file_detection_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='license',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='references',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='file',
            name='markdown_file',
            field=models.FileField(max_length=512, null=True, upload_to=siemrules.siemrules.models.upload_to_func),
        ),
    ]
