# Generated by Django 5.1.4 on 2025-04-03 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siemrules', '0007_file_license_file_references_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='ignore_embedded_relationships_smo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='file',
            name='ignore_embedded_relationships_sro',
            field=models.BooleanField(default=False),
        ),
    ]
