# Generated by Django 5.1.4 on 2025-04-04 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siemrules', '0008_file_ignore_embedded_relationships_smo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='status',
            field=models.CharField(default='experimental', max_length=20),
        ),
    ]
