# Generated by Django 5.1.4 on 2025-04-09 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siemrules', '0009_file_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='ai_provider',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.RemoveField(
            model_name='file',
            name='confidence',
        ),
    ]
