# Generated by Django 5.1.4 on 2025-04-11 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siemrules', '0010_alter_file_ai_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='data',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='type',
            field=models.CharField(choices=[('file', 'File'), ('correlation', 'Correlation')], default='file', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='file',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='siemrules.file'),
        ),
    ]
