# Generated by Django 5.1.4 on 2025-04-22 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siemrules', '0011_job_data_job_type_alter_job_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='status',
        ),
    ]
