# Generated by Django 5.1.4 on 2025-04-29 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siemrules', '0013_alter_file_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='level',
            field=models.CharField(default=None, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='status',
            field=models.CharField(default=None, max_length=24, null=True),
        ),
    ]
