# Generated by Django 5.1.4 on 2025-05-26 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siemrules', '0017_alter_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='type',
            field=models.CharField(choices=[('file.sigma', 'File Sigma'), ('file.file', 'File File'), ('file.prompt', 'File Text'), ('correlation.sigma', 'Correlation Sigma'), ('correlation.prompt', 'Correlation Prompt')], default='file.sigma', max_length=20),
        ),
    ]
