# Generated by Django 5.2.1 on 2025-06-26 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siemrules', '0019_alter_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='type',
            field=models.CharField(choices=[('file.sigma', 'File Sigma'), ('file.file', 'File File'), ('file.prompt', 'File Text'), ('correlation.sigma', 'Correlation Sigma'), ('correlation.prompt', 'Correlation Prompt'), ('base.modify', 'Base Modify'), ('correlation.modify', 'Correlation Modify'), ('duplicate-rule', 'Duplicate Rule')], default='file.sigma', max_length=20),
        ),
    ]
