# Generated by Django 5.2.4 on 2025-10-09 14:33

import siemrules.siemrules.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siemrules', '0020_alter_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='pdf_file',
            field=models.FileField(max_length=1024, null=True, upload_to=siemrules.siemrules.models.upload_to_func),
        ),
    ]
