# Generated by Django 5.2.4 on 2025-10-10 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siemrules', '0021_file_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='txt2detection_data',
            field=models.JSONField(default=None, null=True),
        ),
    ]
