# Generated by Django 5.2.7 on 2025-10-21 13:00

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siemrules', '0022_file_txt2detection_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, unique=True)),
                ('defang', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('ai_provider', models.CharField(blank=True, max_length=256, null=True)),
                ('ai_create_attack_flow', models.BooleanField(default=False)),
                ('ai_create_attack_navigator_layer', models.BooleanField(default=False)),
                ('ignore_embedded_relationships', models.BooleanField(default=False)),
                ('ignore_embedded_relationships_smo', models.BooleanField(default=False)),
                ('ignore_embedded_relationships_sro', models.BooleanField(default=False)),
                ('include_embedded_relationships_attributes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), default=list, size=None)),
                ('extract_text_from_image', models.BooleanField(default=False)),
                ('generate_pdf', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='file',
            name='ai_provider',
        ),
        migrations.RemoveField(
            model_name='file',
            name='defang',
        ),
        migrations.RemoveField(
            model_name='file',
            name='extract_text_from_image',
        ),
        migrations.RemoveField(
            model_name='file',
            name='ignore_embedded_relationships',
        ),
        migrations.RemoveField(
            model_name='file',
            name='ignore_embedded_relationships_smo',
        ),
        migrations.RemoveField(
            model_name='file',
            name='ignore_embedded_relationships_sro',
        ),
        migrations.AddField(
            model_name='file',
            name='profile',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='siemrules.profile'),
        ),
    ]
