# Generated by Django 5.2.7 on 2025-10-23 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siemrules', '0023_profile_remove_file_ai_provider_remove_file_defang_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='profile',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default',), name='unique_default_profile'),
        ),
    ]
