# Generated by Django 5.2.7 on 2025-10-31 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siemrules', '0024_profile_is_default_profile_unique_default_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='ai_create_attack_flow',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='ai_create_attack_navigator_layer',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='defang',
        ),
    ]
