# Generated by Django 5.2.7 on 2025-11-03 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siemrules', '0025_remove_profile_ai_create_attack_flow_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
