# Generated by Django 5.2.8 on 2025-11-17 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siemrules', '0026_alter_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='file',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='siemrules.file'),
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_id', models.CharField(max_length=48)),
                ('modified', models.CharField(max_length=30)),
                ('action', models.CharField(choices=[('create', 'Create'), ('modify', 'Modify')], max_length=16)),
                ('type', models.CharField(choices=[('sigma', 'Sigma'), ('prompt', 'Prompt'), ('file', 'File'), ('clone', 'Clone'), ('revert', 'Revert')], max_length=16)),
                ('rule_type', models.CharField(choices=[('base', 'Base Rule'), ('correlation', 'Correlation Rule')], max_length=32)),
                ('prompt', models.TextField(default=None, null=True)),
                ('cloned_from', models.CharField(default=None, max_length=100, null=True)),
                ('reverted_to', models.DateTimeField(default=None, null=True)),
                ('file', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='siemrules.file')),
                ('job', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='siemrules.job')),
            ],
            options={
                'verbose_name': 'Version entry',
                'verbose_name_plural': 'Version entries',
                'ordering': ['-modified'],
            },
        ),
    ]
