# Generated by Django 5.2.8 on 2025-11-18 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siemrules', '0027_alter_job_file_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='version',
            name='reverted_to',
        ),
        migrations.AddField(
            model_name='version',
            name='base_version',
            field=models.CharField(default=None, null=True),
        ),
    ]
