# Generated by Django 5.2.8 on 2026-01-06 11:01

import contextlib
from django.db import migrations, models
from django.conf import settings
import django.db.models.deletion
from dogesec_commons.identity.serializers import IdentitySerializer


def list_identities(self, request, *args, **kwargs):
    from siemrules.siemrules.arangodb_helpers import ArangoDBHelper

    helper = ArangoDBHelper(settings.VIEW_NAME, None)
    query = """
        FOR doc IN siemrules_vertex_collection
        FILTER doc.type == "identity" AND doc._is_latest == TRUE
        RETURN KEEP(doc, KEYS(doc, TRUE))
        """
    return helper.execute_query(query, paginate=False)


def make_default_identity(apps, schema_editor):
    from siemrules.worker.tasks import upload_objects
    import uuid
    from types import SimpleNamespace

    # with contextlib.suppress(Exception):
    upload_objects(
        SimpleNamespace(id="migration-default-identity"),
        {"type": "bundle", "id": "bundle--" + str(uuid.uuid4()), "objects": []},
        {},
    )
    return create_or_get_identity(settings.STIX_IDENTITY)

def create_or_get_identity(identity_data):
    from dogesec_commons.identity.models import Identity
    identity_instance = Identity.objects.filter(id=identity_data["id"]).first()
    if not identity_instance:
        serializer = IdentitySerializer(data=identity_data)
        identity_instance = serializer.is_valid(raise_exception=True)
        identity_instance: Identity = serializer.save()
    return identity_instance

def copy_identities_to_local(apps, schema_editor):
    from dogesec_commons.identity.models import Identity as CommonIdentity
    from siemrules.siemrules.models import File

    FileType: type[File] = apps.get_model("siemrules", "File")

    Identity: type[CommonIdentity] = apps.get_model("dogesec_identity", "Identity")
    SYSTEM_IDENTITIES = [
        "identity--72e906ce-ca1b-5d73-adcd-9ea9eb66a1b4",
        "identity--9779a2db-f98c-5f4b-8d08-8ee04e02dbb5",
        "identity--a4d70b75-6f4a-5d19-9137-da863edd33d7",
    ]
    identities = list_identities(None, None)

    for identity_data in identities:
        if identity_data["id"] in SYSTEM_IDENTITIES:
            continue
        identity_instance = create_or_get_identity(identity_data)
        FileType.objects.filter(identity_json__id=identity_data["id"]).update(
            identity=identity_instance
        )


class Migration(migrations.Migration):

    dependencies = [
        ("siemrules", "0028_remove_version_reverted_to_version_base_version"),
        ("dogesec_identity", "__first__"),
    ]
    operations = [
        migrations.RenameField(
            model_name="file",
            old_name="identity",
            new_name="identity_json",
        ),
        migrations.RunPython(
            code=make_default_identity,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddField(
            model_name="file",
            name="identity",
            field=models.ForeignKey(
                default=settings.STIX_IDENTITY["id"],
                on_delete=django.db.models.deletion.CASCADE,
                to="dogesec_identity.identity",
            ),
        ),
        migrations.RunPython(
            code=copy_identities_to_local,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
