# Generated by Django 5.2.11 on 2026-04-22 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogesec_identity', '0001_initial'),
        ('siemrules', '0029_migrate_to_local_identities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='identity_json',
        ),
        migrations.AlterField(
            model_name='file',
            name='identity',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dogesec_identity.identity'),
        ),
    ]
